// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhMEmPWB7IlC7oVrCOjMrRRWHY7_JP4M',
    appId: '1:799923700168:web:dae71da0ecf695ac3600fd',
    messagingSenderId: '799923700168',
    projectId: 'petapplication-e28d2',
    authDomain: 'petapplication-e28d2.firebaseapp.com',
    storageBucket: 'petapplication-e28d2.appspot.com',
    measurementId: 'G-J43SZXMW2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGEmExepBmFDXOiQ8GPBLtv1Mlzzl5bc',
    appId: '1:799923700168:android:221c24043d4733fe3600fd',
    messagingSenderId: '799923700168',
    projectId: 'petapplication-e28d2',
    storageBucket: 'petapplication-e28d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTrhbZiLY-hyPJ2s6HQA4hk4bCSxWu0qU',
    appId: '1:799923700168:ios:75515ff1c8598f303600fd',
    messagingSenderId: '799923700168',
    projectId: 'petapplication-e28d2',
    storageBucket: 'petapplication-e28d2.appspot.com',
    iosClientId: '799923700168-0uh6ur3ivtkhr07vc71csc516b6tg77u.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTrhbZiLY-hyPJ2s6HQA4hk4bCSxWu0qU',
    appId: '1:799923700168:ios:75515ff1c8598f303600fd',
    messagingSenderId: '799923700168',
    projectId: 'petapplication-e28d2',
    storageBucket: 'petapplication-e28d2.appspot.com',
    iosClientId: '799923700168-0uh6ur3ivtkhr07vc71csc516b6tg77u.apps.googleusercontent.com',
    iosBundleId: 'com.example.petapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMhMEmPWB7IlC7oVrCOjMrRRWHY7_JP4M',
    appId: '1:799923700168:web:889245190320ab2c3600fd',
    messagingSenderId: '799923700168',
    projectId: 'petapplication-e28d2',
    authDomain: 'petapplication-e28d2.firebaseapp.com',
    storageBucket: 'petapplication-e28d2.appspot.com',
    measurementId: 'G-T3R3T202QT',
  );

}